### PR TITLE
fix graph rendering in recent piwik versions. working with piwik 2.15.0.

### PR DESCRIPTION
**Pull request by foscarini**
Fixes the issues #22 and #19

screen shot 2015-11-13 at 12 50 54 am

Tested with piwik 2.15.0 migrated from 2.1, nginx and PHP 5.6.14.

### CODE REVIEW

**Comment by fritteli** [comment]
I applied this patch to my Piwik installation (version 2.15.0 with IPv6Usage 0.7.1 / Apache 2.2.31 / PHP 5.6.14), and now everything works as expected. Thank you very much for fixing it.
Please, @halfdan , merge this PR and release a new official version of the plugin!

**Comment by halfdan** [comment]
Currently OOO but will merge when I get a chance and release a new version.
Thanks so much for creating the pull request!

**Comment by michaellass** [comment]
Any news on this? I'm running the plugin with this change since this pull request is open and it's working great.

**Comment by Occupied** [comment]
This fix also works with Piwik 2.16.0.
Thanks for posting it!

**Comment by halfdan** [comment]
Sorry folks, didn't realise this was still open. Just merged and tagged a new version. Should be showing up in your Piwik soon. Thanks @foscarini!

**Pull request merged**
